site_name: Muddling through Medical Imaging
site_url: https://salcedoe.github.io/MtMdocs/
repo_url: https://github.com/salcedoe/MtMtools
nav:
  - Home: index.md
  - Setup:
    - Software: setup/softwareOverview.md
    - Installing MATLAB: setup/matlabInstallation.md
    - Github Repositories: setup/githubRepoInstallation.md
    - Computer Settings: setup/computerSetup.md
  - Reference:
    - MATLAB stuff: reference/MATLABReferencePages.md
    - MtM Course Functions: reference/courseFunctions.md
  - MATLAB Basics:
    - Introduction:
         - Muddling Through MATLAB: matlabBasics/MatlabIntro.md
         - The MATLAB Interface: matlabBasics/matlabInterface.md
    - Basic Concepts:
      - Data: matlabBasics/DataOverview.md
      - Variables: matlabBasics/Variables.md
      - Functions: matlabBasics/Functions.md
      - Array Assignment: matlabBasics/ArrayAssignmentOverview.md
      - Binary Numbers: matlabBasics/BinaryNumbers.md
    - Basic Data Classes:
       - Numeric Arrays: matlabBasics/Numeric.md
       - Logical Arrays: matlabBasics/Logical.md
       - Character Arrays: matlabBasics/Character.md
    - Complex Data Classes: 
       - Cells: matlabBasics/Cell.md
       - Strings: matlabBasics/Strings.md
       - Structures: matlabBasics/Structures.md
       - Tables: matlabBasics/Tables.md
    - Simple Programming: 
      - Control Flow: matlabBasics/ControlFlow.md
      - Files and Folders: matlabBasics/FilesFolders.md
    - Plotting: 
      - Plotting Components: matlabBasics/PlottingComponents.md
      - Plotting Basics: matlabBasics/PlottingBasics.md   
      - Plotting Overlays and Tiles: matlabBasics/PlottingOverlaysTiles.md
      - Plotting Group Statistics: dataProcessing/groupStats.md
    - Scripts:
      - Control Flow and Functions in Scripts: matlabBasics/scripts/Control_Flow_Functions.md
  - Data Processing: 
    - dataProcessing/index.md
    - Data Types: dataProcessing/dataTypes.md
    - Tidy Data: dataProcessing/tidyData.md
    - Group Statistics: dataProcessing/groupStats.md
    - Sampling and Distributions: dataProcessing/SamplesDistributions.md
    - Hypothesis Testing: dataProcessing/HypTesting.md
  - Imaging:
    - imaging/index.md 
    - Imaging Concepts:
      - Light: imaging/electromagneticRadiation.md
      - Human Vision: imaging/humanVision.md
      - Color Models: imaging/colorModels.md
    - Imaging with Light:
      - Digital Photography: imaging/digitalPhotography.md
      - Digital Microscopy: imaging/digitalMicroscopy.md
    - Medical Imaging:
      - Introduction: imaging/medicalImagingIntro.md
      - X-ray Imaging: imaging/XrayImaging.md
      - CT Imaging: imaging/CTImaging.md
  - Image Processing:
    - 2D Image Processing:
      - Grayscale Images: imageProcessing/ImageIntro.md
      - Image Enhancement: imageProcessing/ImageEnhancement.md
      - Image Segmentation: imageProcessing/ImageSegmentation.md
      - Segmentation Cleanup: imageProcessing/ImageSegmentationCleanup.md
      - Region Processing: imageProcessing/ImageRegionProcessing.md
      - RGB Images: imageProcessing/ImageRGB.md
    
  - Volume Processing: 
    - Overview: volumeProcessing/volumeOverview.md
    - Loading Volumes:
      - Medical File Formats: volumeProcessing/volumeMedicalFileFormats.md
      - Loading Confocal Datasets: volumeProcessing/volumeLoadingMicroscopy.md
    - Inspecting Volumes: volumeProcessing/volumeVisualization.md
    - 3D Visualization: volumeProcessing/volumeRendering.md
      # - Color Stacks: volumeProcessing/ImageStacksColor.md
      # - Volume Visualization: volumeProcessing/VolumeVisualization.md
      # - Volume Segmentation: volumeProcessing/VolumeSegmentation.md
      # - Volume Registration: volumeProcessing/VolumeRegistration.md
      # - Volume Analysis: volumeProcessing/VolumeAnalysis.md    
    #- Volume Imaging:
      #- Introduction: volumeProcessing/medicalImagingIntro.md
  - 3D Slicer:
    - Introduction: slicer/InterfaceIntro.md
    - Customize Slicer: slicer/CustomizeSlicer.md
    - Data Exploration:
      - CTChest: slicer/CTChestExplore.md
      - PET CT (Multi-modal Dataset): slicer/CTPETExplore.md
      - CT MRI: slicer/CTMRExplore.md
      - Import DICOM datasets: slicer/ImportDICOMDataset.md
    - Volume Segmentation:
      - CTACardio: slicer/CTACardioSegment.md
      - MR Tumors: slicer/MRTumorSegment.md
      - CT Femur: slicer/CTFemurSegment_9553F.md
      - Total Segmentator: slicer/TotalSegmentator.md
    - Surface Models:
      - Creating Surface Models: slicer/CreateModels.md
      - Exporting Models: slicer/ExportModels.md
    - Generating Animations:
      #- Screen Capture Module: slicer/ScreenCapture.md
      - Image sequence to video (MAC): slicer/ImageSequenceToVideo.md
theme: 
  name: material
  icon: 
    logo: material/skull-scan
  favicon: assets/skull-scan-blue.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.instant
    - navigation.top
    - navigation.path
    #- toc.integrate
    - search.suggest
    - search.highlight
    - search.share
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - content.code.select
  language: en
  palette:   
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: black
      accent: amber
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: black   
      accent: cyan
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower      
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
plugins:
  - search
  - table-reader
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css
copyright: |
  &copy; 2025 <a href="https://github.com/salcedoe"  target="_blank" rel="noopener">Ernesto Salcedo</a>
